In [42]:
import numpy as np

In [43]:
X = np.array([[1, 0, 1, 0],
     [1, 0, 1, 1],
     [0, 1, 0, 1]])
Y = np.array([[1],
             [1],
             [0]])
lr = 1

In [44]:
'''
np.random.uniform(low=0, high=1, size=(4,3))
bh = np.random.uniform(low=0, high=1, size=(3,1))
wout = np.random.uniform(low=0, high=1, size=(3,1))
bout = np.random.uniform(low=0, high=1, size=(1,1))
print(wh,bh)
'''

'\nnp.random.uniform(low=0, high=1, size=(4,3))\nbh = np.random.uniform(low=0, high=1, size=(3,1))\nwout = np.random.uniform(low=0, high=1, size=(3,1))\nbout = np.random.uniform(low=0, high=1, size=(1,1))\nprint(wh,bh)\n'

In [45]:
wh = np.array([[0.42, 0.88, 0.55],
     [0.1, 0.73, 0.68],
     [0.6, 0.18, 0.47],
     [0.92, 0.11, 0.52]])
bh = np.array([0.46, 0.72, 0.08])
wout = np.array([[0.3],
                [0.25], 
                [0.23]])
bout = np.array([0.69])

In [46]:
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))

In [47]:
def sigmoid_der(xprime):
    return xprime * (1 - xprime)

In [48]:
hidden_layer = X.dot(wh) + bh
print(hidden_layer)
hidden_layer = sigmoid(hidden_layer)
print(hidden_layer)

[[ 1.48  1.78  1.1 ]
 [ 2.4   1.89  1.62]
 [ 1.48  1.56  1.28]]
[[ 0.81457258  0.85569687  0.75026011]
 [ 0.9168273   0.86875553  0.83479513]
 [ 0.81457258  0.82635335  0.78244978]]


In [49]:
output_layer = hidden_layer.dot(wout) + bout
print(output_layer)
output_layer = sigmoid(output_layer)
print(output_layer)

[[ 1.32085581]
 [ 1.37423995]
 [ 1.32092356]]
[[ 0.78932406]
 [ 0.79806432]
 [ 0.78933532]]


In [50]:
err_output = Y - output_layer
print(err_output)

[[ 0.21067594]
 [ 0.20193568]
 [-0.78933532]]


In [51]:
slope_out = sigmoid_der(output_layer)
print(slope_out)

[[ 0.16629159]
 [ 0.16115766]
 [ 0.16628507]]


In [52]:
slope_hidden = sigmoid_der(hidden_layer)
print(slope_hidden)

[[ 0.15104409  0.12347974  0.18736988]
 [ 0.076255    0.11401936  0.13791222]
 [ 0.15104409  0.14349349  0.17022212]]


In [53]:
d_output = err_output * slope_out
print(d_output)

[[ 0.03503364]
 [ 0.03254348]
 [-0.13125468]]


In [55]:
err_hidden = d_output.dot(wout.T)
print(d_output.shape, wout.shape)
print(err_hidden)

(3, 1) (3, 1)
[[ 0.01051009  0.00875841  0.00805774]
 [ 0.00976304  0.00813587  0.007485  ]
 [-0.0393764  -0.03281367 -0.03018858]]


In [56]:
d_hidden = err_hidden*slope_hidden
print(d_hidden)

[[ 0.00158749  0.00108149  0.00150978]
 [ 0.00074448  0.00092765  0.00103227]
 [-0.00594757 -0.00470855 -0.00513876]]


In [57]:
wout = wout + hidden_layer.T.dot(d_output) * lr
print(wout)

[[ 0.25145773]
 [ 0.19978776]
 [ 0.18075129]]


In [58]:
wh = wh+ X.T.dot(d_hidden) * lr
print(wh)

[[ 0.42233197  0.88200913  0.55254205]
 [ 0.09405243  0.72529145  0.67486124]
 [ 0.60233197  0.18200913  0.47254205]
 [ 0.91479691  0.1062191   0.51589351]]


In [59]:
bh = bh + np.sum(d_hidden, axis=0) * lr
bout = bout + np.sum(d_output, axis=0)*lr
print(bh, bout)

[ 0.45638439  0.71730058  0.07740329] [ 0.62632244]
